@CredentialsApi_HostAddress = https://localhost:7107
@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIzIiwiZW1haWwiOiJ0ZXN0dXNlcjFAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzY3OTg4NzA5LCJpc3MiOiJDcmVkZW50aWFsc0FwaSIsImF1ZCI6IkNyZWRlbnRpYWxzQXBpVXNlcnMifQ.kcYDckOraQ90ygPodPUU9gg1H5RfqZL9XBIlPSiPET0

###
# 1) Register 
POST {{CredentialsApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "Email": "testuser1@example.com",
  "Password": "Test@1234"
}

###
# 2) Login 
POST {{CredentialsApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "Email": "testuser1@example.com",
  "Password": "Test@1234"
}

###
# 3) Create 
POST {{CredentialsApi_HostAddress}}/api/secure-items
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "Title": "My Secure Item",
  "Content": "This is a secure item description."
}

###
# 4) GetById 
GET {{CredentialsApi_HostAddress}}/api/secure-items/8
Authorization: Bearer {{bearerToken}}
Accept: application/json
###
# 4) GetById 
GET {{CredentialsApi_HostAddress}}/api/secure-items
Authorization: Bearer {{bearerToken}}
Accept: application/json

###
# 5) Update 
PUT {{CredentialsApi_HostAddress}}/api/secure-items/8
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "Title": "Updated Title",
  "Content": "Updated secure content."
}

###
# 6) Delete 
DELETE {{CredentialsApi_HostAddress}}/api/secure-items/8
Authorization: Bearer {{bearerToken}}

###
# 7) Search (q, page, pageSize)
GET {{CredentialsApi_HostAddress}}/api/secure-items/search?q=Secure&page=1&pageSize=10
Authorization: Bearer {{bearerToken}}
Accept: application/json