@CredentialsApi_HostAddress = http://localhost:5153

GET {{CredentialsApi_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{CredentialsApi_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "Email": "testUser",
  "Password": "Test@1234"
}